### ISSUE TITLE
URL Remove -and- 

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Africology-and-African-American-Studies#4]
@lidopaglia I don't like to have the and in the url. Can we remove it?

**Comment by lidopaglia** [comment]
Hey @tu-chill we can certainly do this. 

Couple questions though...

1. Do you want this change made to just the production URL or should we change the name in all resources related to the site as well (S3, github, travis, etc.)? I am a fan of keeping things consistent (leaning to the latter option) but doing so will involve a bit more work.

2. There's other sites that have 'and' in the name too:

    - Africology-and-African-American-Studies
    - Center-for-the-Study-of-Force-and-Diplomacy
    - Center-for-Vietnamese-Philosophy-Culture-and-Society
    - Gender-Sexuality-and-Womens-Studies
    - Geography-and-Urban-Studies
    - Greek-and-Roman-Classics
    
  Should they all drop the 'and' from their name as well?

Just curious, what is the benefit of doing this? I'm definitely not opposed to making the necessary changes but just want to understand the goal.

**Comment by tu-chill** [comment]
This appears to be an obsessive compulsion getting the best of me. I usually strip out little words because the make the links too long for my taste. But I think we can leave them the way they are and if we need vanity shorter URLs we can create them.
